#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server:


if [ "$#" -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path=$1
IP_address=$2
username=$3
ssh_path=$4

scp -o StrictHostKeyChecking=no -i "$ssh_path" "$file_path" "$username@$IP_address:~/"
