#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get intall -y nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo nginx -t
sudo service nginx reload
curl -sI http://localhost/non_existent_page
exit 0
