#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get intall -y nginx
#sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/a location /redirect_me {\n    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
custom_404="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s|listen 80 default_server;|$custom_404|" /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart
sudo ufw allow 'Nginx HTTP'
exit 0
