#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get intall -y nginx
#sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
redirection_line="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4;"
sudo sed -i "s/server_name _;/$redirection_line/" /etc/nginx/sites-enabled/default
# Custom 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
custom_404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$custom_404/" /etc/nginx/sites-enabled/default

sudo service nginx restart
