#!/usr/bin/env bash
# A Bash script that displays lines containing the bash word
# Requirements:

#	You cannot use pgrep
#	The third line of your script must be # shellcheck disable=SC2009

ps auxf | grep "bash"
