#!/usr/bin/env bash
# A Bash script that displays To infinity and beyond indefinitely.

# Requirements:

#	In between each iteration of the loop, add a sleep 2

i=0
while [ $i -lt 3 ]
do
	echo "To infinity and beyond"
	sleep 2
done
