#!/usr/bin/env bash

# Prints Best School 10 times but for the 9th iteration, displays Best
# School and then Hi on a new line

word="Best School"
i=1

while [ $i -le 10 ]
do
        echo "$word"
	if [ $i == 9 ]
	then
		echo "Hi"
	fi
	i=$(( i + 1 ))
done
