#!/usr/bin/env bash
# A bash script that prints loops 10 times and displays certain words at certain numbers

word1="Best School"
word2="bad luck"
word3="good luck"
i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "$word2"
	elif [ $i -eq 8 ]
	then
		echo "$word3"
	else
        	echo "$word1"
	fi
	i=$(( i + 1 ))
done
